## Pytorch Tensor Operations

In [1]:
import torch

## Arithmetic Element-wise Operations

In [2]:
# 사칙연산
a = torch.FloatTensor([[1, 2],
                      [3, 4]])
b = torch.FloatTensor([[2, 2],
                      [3, 3]])

In [3]:
print(a+b)

tensor([[3., 4.],
        [6., 7.]])


In [4]:
print(a-b)

tensor([[-1.,  0.],
        [ 0.,  1.]])


In [5]:
print(a*b)

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [6]:
print(a/b)

tensor([[0.5000, 1.0000],
        [1.0000, 1.3333]])


In [7]:
a == b

tensor([[False,  True],
        [ True, False]])

In [8]:
a != b

tensor([[ True, False],
        [False,  True]])

In [9]:
# a의 b승
a ** b

tensor([[ 1.,  4.],
        [27., 64.]])

## Inplace Operations
함수 뒤에 언더바를 붙여서 새롭게 메모리를 할당하는 것이 아니라, 기존 자리에 결과를 넣는다.

In [10]:
print(a)

tensor([[1., 2.],
        [3., 4.]])


In [11]:
print(a.mul(b)) # a*b

tensor([[ 2.,  4.],
        [ 9., 12.]])


In [12]:
print(a) # 변동사항 없음

tensor([[1., 2.],
        [3., 4.]])


In [13]:
#a의 주소값에 결과를 덮어씌운다.
print(a.mul_(b)) 
print(a)

tensor([[ 2.,  4.],
        [ 9., 12.]])
tensor([[ 2.,  4.],
        [ 9., 12.]])


## Sum, Mean (Dimension Reducing Operations)

In [14]:
x = torch.FloatTensor([[1, 2],
                      [3, 4]])

In [17]:
print(x.sum()) #더한 스칼라 값이(1차원) 나옴

tensor(10.)


In [19]:
print(x.mean()) #평균의 스칼라 값(1차원)이 나옴

tensor(2.5000)


특정 차원에 대해서만 sum을 하고 싶다면?

In [23]:
# 세로로 찌부
x.sum(dim=0)

tensor([4., 6.])

In [24]:
# 가로로 찌부
x.sum(dim=-1)

tensor([3., 7.])

## Broadcast in Operations

In [25]:
# 모양이 다른 텐서간의 연산
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3, 4]])

### Tensor + Scalar

In [27]:
x = torch.FloatTensor([[1,2],[3,4]])
y = 1

z = x+y

print(x)
print(z)
print(z.size())

tensor([[1., 2.],
        [3., 4.]])
tensor([[2., 3.],
        [4., 5.]])
torch.Size([2, 2])


### Tensor+Vector

In [28]:
x = torch.FloatTensor([[1, 2],
                      [4, 8]])
y = torch.FloatTensor([[3,
                       5]])

print(x.size())
print(y.size())

torch.Size([2, 2])
torch.Size([1, 2])


In [29]:
x = torch.FloatTensor([[[1, 2]]])
y = torch.FloatTensor([[3,
                      5]])
z = x+y
print(z)
print(z.size())

tensor([[[4., 7.]]])
torch.Size([1, 1, 2])


### Tensor + Tensor

In [31]:
x = torch.FloatTensor([[1, 2]])
y = torch.FloatTensor([[3],
                      [5]])

print(x.size())
print(y.size())

torch.Size([1, 2])
torch.Size([2, 1])


In [33]:
z = x + y
print(z)
print(z.size())

tensor([[4., 5.],
        [6., 7.]])
torch.Size([2, 2])


### Failure Case

In [42]:
# 브로드캐스트 때문에 에러는 안나고 값은 이상한 현상이 자주 발생한다.

x = torch.FloatTensor([[[1,2],
                      [4,8]]])
y = torch.FloatTensor([[1,2,3],
                       [4,5,6],
                       [7,8,9]])

In [43]:
print(x.size())
print(y.size())

torch.Size([1, 2, 2])
torch.Size([3, 3])


In [45]:
# 브로드캐스트를 적용할 수 없음
z = x + y

RuntimeError: The size of tensor a (2) must match the size of tensor b (3) at non-singleton dimension 2