## Pytorch Tensor Manipulations

In [8]:
import torch

## Tensor Shaping


#### reshape : Change Tensor Shape

In [9]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                        [[5, 6],
                        [7, 8]],
                        [[9, 10],
                       [11, 12]]])

In [10]:
print(x.size())

torch.Size([3, 2, 2])


In [11]:
# reshape 괄호 안에 내가 원하는 텐서 사이즈 넣기
print(x.reshape(12))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [12]:
print(x.reshape(-1))

tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.])


In [14]:
# reshape로 matrix 만들기
print(x.reshape(3, 4))
print(x.reshape(3, -1))

tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])
tensor([[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]])


In [16]:
print(x.reshape(3, 1, 4))
print(x.reshape(-1, 1, 4))

tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])
tensor([[[ 1.,  2.,  3.,  4.]],

        [[ 5.,  6.,  7.,  8.]],

        [[ 9., 10., 11., 12.]]])


In [18]:
# 4차원 텐서 만들기
print(x.reshape(3, 2, 2, 1))

tensor([[[[ 1.],
          [ 2.]],

         [[ 3.],
          [ 4.]]],


        [[[ 5.],
          [ 6.]],

         [[ 7.],
          [ 8.]]],


        [[[ 9.],
          [10.]],

         [[11.],
          [12.]]]])


+) view() 라는 함수는 reshape() 와 같다고 할 수 있다.

### squeeze : Remove dimension which has only one element

In [19]:
# 어느 특정 차원이 1이면 없애는 과정
x = torch.FloatTensor([[[1, 2],
                       [3, 4]]])

In [20]:
print(x.size())

torch.Size([1, 2, 2])


In [23]:
# remove any dimension which has only one element
print(x.squeeze())
print(x.squeeze().size())

tensor([[1., 2.],
        [3., 4.]])
torch.Size([2, 2])


In [26]:
# remove certain deimension, if it has only one element. If it is not, there would be no charge
print(x.squeeze(0).size())
print(x.squeeze(1).size())

torch.Size([2, 2])
torch.Size([1, 2, 2])


### unsqueeze : Insert dimension at certain index

In [30]:
x = torch.FloatTensor ([[1, 2],
                       [3, 4]])
print(x.size())
print(x)

torch.Size([2, 2])
tensor([[1., 2.],
        [3., 4.]])


In [31]:
print(x.unsqueeze(2))
print(x.unsqueeze(2).size())

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
torch.Size([2, 2, 1])


In [33]:
print(x.unsqueeze(-1))
print(x.unsqueeze(-1).size())

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])
torch.Size([2, 2, 1])


In [34]:
print(x.unsqueeze(1))
print(x.unsqueeze(1).size())

tensor([[[1., 2.]],

        [[3., 4.]]])
torch.Size([2, 1, 2])
