### 1. 파이썬 버전 체크

In [1]:
import sys
print(sys.version)

3.7.11 (default, Jul  3 2021, 18:01:19) 
[GCC 7.5.0]


### 2. torch 설치 및 버전 확인하기

In [2]:
import torch
import torch.nn as nn
# !pip3 install torch torchvision

print("Torch version:{}".format(torch.__version__))
print("cuda version: {}".format(torch.version.cuda))
print("cudnn version:{}".format(torch.backends.cudnn.version()))

Torch version:1.9.0+cu102
cuda version: 10.2
cudnn version:7605


### 3. Convert to CUDA tensor : cuda()
실행 전, 런타임 유형변경 -> 'GPU' dont' forget!!

In [3]:
# 1. 바로 텐서에 gpu 선언하기
x = torch.cuda.FloatTensor(2, 2)

x

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [4]:
# 2. 텐서 선언하고 gpu로 보내기
x = torch.FloatTensor(2, 2)
x

tensor([[-2.4954e+20,  3.0735e-41],
        [ 0.0000e+00,  0.0000e+00]])

In [6]:
# 아래를 보면 0번 GPU로 갔음을 확인할 수 있음
x.cuda()

tensor([[-2.4954e+20,  3.0735e-41],
        [ 0.0000e+00,  0.0000e+00]], device='cuda:0')

In [9]:
# 3. 디바이스 지정해서 보내기
d = torch.device('cuda:0')

In [11]:
# 기존 x는 유지된채 새롭게 복사되어 할당됨
x.cuda(device=d)

tensor([[-2.4954e+20,  3.0735e-41],
        [ 0.0000e+00,  0.0000e+00]], device='cuda:0')

In [13]:
# 따라서 기존 x는 'cpu'임을 확인할 수 있음 
x.device

device(type='cpu')

### 4. Convert to CUDA tensor: to ( )

x.cuda는 좀 아재스러운 방법.... x.to는 덜 아재스러운 방법

In [14]:
x.to(device=d) 

tensor([[-2.4954e+20,  3.0735e-41],
        [ 0.0000e+00,  0.0000e+00]], device='cuda:0')

### 5. Convert to CPU tensor from CUDA tensor

In [17]:
# gpu -> cpu

x = torch.cuda.FloatTensor(2, 2)
x = x.cpu()

In [18]:
d = torch.device('cpu')
x = x.to(d)

### 6. Move model from CPU to GPU

In [19]:
def print_params(model):
  for p in model.parameters():
    print(p)

In [20]:
linear = nn.Linear(3, 2)

print_params(linear)

Parameter containing:
tensor([[ 0.4798, -0.4905,  0.2962],
        [ 0.2722, -0.5658,  0.2619]], requires_grad=True)
Parameter containing:
tensor([ 0.3965, -0.5450], requires_grad=True)


In [21]:
linear = linear.cuda()

print_params(linear)

Parameter containing:
tensor([[ 0.4798, -0.4905,  0.2962],
        [ 0.2722, -0.5658,  0.2619]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.3965, -0.5450], device='cuda:0', requires_grad=True)


In [22]:
linear = linear.cpu()
print_params(linear)

Parameter containing:
tensor([[ 0.4798, -0.4905,  0.2962],
        [ 0.2722, -0.5658,  0.2619]], requires_grad=True)
Parameter containing:
tensor([ 0.3965, -0.5450], requires_grad=True)


In [23]:
d = torch.device('cuda:0')
linear = linear.to(d)

print_params (linear)

Parameter containing:
tensor([[ 0.4798, -0.4905,  0.2962],
        [ 0.2722, -0.5658,  0.2619]], device='cuda:0', requires_grad=True)
Parameter containing:
tensor([ 0.3965, -0.5450], device='cuda:0', requires_grad=True)


In [25]:
# error -> 모델은 디바이스라는 메서드를 제공하지 않는다.
linear.device

AttributeError: ignored

### 7. Tricks
연산하고 싶은데 어떤 디바이스에 있는지 궁금한 경우

In [27]:
x = torch.cuda.FloatTensor(2, 2)

In [29]:
#x와 같은 타입이면서 같은 디바이스 형태의 텐서를 만들어줌
x.new(2, 2) 

tensor([[ 0.3965, -0.5450],
        [ 0.2962,  0.2722]], device='cuda:0')

In [30]:
torch.zeros_like(x)

tensor([[0., 0.],
        [0., 0.]], device='cuda:0')

In [31]:
torch.ones_like(x)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')

In [32]:
list(linear.parameters())[0].new(2, 2)

tensor([[1., 1.],
        [1., 1.]], device='cuda:0')