# Pytorch Tensor

In [1]:
import torch

## Tensor Allocation

In [3]:
#float tensor 선언 (가장 많이 쓰임 / 32bit)
ft = torch.FloatTensor([[1,2],
                       [3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [6]:
#long tensor 선언 (정수를 담는 tensor)
#인덱스 값을 담을 때 많이 사용

lt = torch.LongTensor([[1,2],
                      [3,4]])

lt

tensor([[1, 2],
        [3, 4]])

In [10]:
#byte tensor 선언 (0,1을 담는) <-> True, False를 담는 boolean tensor도 있음

bt = torch.ByteTensor([[1, 0],
                      [0, 1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

In [12]:
# 다르게 선언하는 방식
# 값은 아무거나 랜덤하게 상관없지만, 사이즈는 일정했으면 좋겠다 !

x = torch.FloatTensor(3, 2)
x

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Numpy Compatibility 
#### 토치 장점 :  파이토치는 넘파이와 호환이 잘된다 

In [13]:
import numpy as np

x = np.array([[1, 2],
             [3, 4]])
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [15]:
#from numpy to torch

x = torch.from_numpy(x)
print(x, type(x))

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [16]:
#from torch to numpy

x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


## Tensor Type-casting

- 주의 : 연산시 float끼리, long끼리 같은 형식끼리 연산해주어야 한다.
- 형을 변환해주어야 할 때 어떻게?



In [22]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [23]:
ft.float()

tensor([[1., 2.],
        [3., 4.]])

In [24]:
#Byte Tensor로 형변환

torch.FloatTensor([1, 0]).byte()

tensor([1, 0], dtype=torch.uint8)

## Get Shape

In [25]:
x = torch.FloatTensor([[[1, 2],
                        [3, 4]],
                       [[5, 6],
                        [7, 8]],
                       [[9, 10],
                        [11, 12]]])

In [26]:
x

tensor([[[ 1.,  2.],
         [ 3.,  4.]],

        [[ 5.,  6.],
         [ 7.,  8.]],

        [[ 9., 10.],
         [11., 12.]]])

In [32]:
# 내가 만든 tensor의 사이즈 확인 (get number of dimensions in the tensor)

print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


In [34]:
# dimensions 개수
print(x.dim())
print(len(x.size()))

3
3


In [35]:
# 특정 dimensions 개수 확인
print(x.size(1))
print(x.shape[1])

2
